### PR TITLE
Add Badge

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**
*note: you should probably also add your repo in [this](https://github.com/sindresorhus/awesome) repo as well.*

### CODE REVIEW

**Comment by NeonGamerBot-QK** [comment]
@endo9001

**Comment by NeonGamerBot-QK** [comment]
image

**Comment by endo9000** [comment]
good idea! thanks! 
will do as soon as the main stuff is worked out. 🙏

**Comment by NeonGamerBot-QK** [comment]
?

**Comment by endo9000** [comment]
well the list isnt yet sorted. 
i still need to add the rest thats available (not a lot but plenty)
after that i would add the repo to awesome repo. 👍

**Pull request merged**
